# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brendon Smith | Udacity
email: brendon.w.smith@gmail.com
description: >- # ignore newlines until "baseurl:"
  GitHub Pages Jekyll website for Udacity code on GitHub
url: "https://br3ndonland.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/udacity" # the subpath of your site, e.g. /blog
# twitter_username:
github_username:  br3ndonland

# Build settings
# kramdown and rouge highlighter now enabled by default
# theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

include:
  - .htaccess

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
